// Nombres alternativos en español (y otras variantes) para cada país.
// La clave es el nombre en inglés usado en todosPaises.
export const nombresAlternativos = {
  Afghanistan: ['Afganistán'],
  Algeria: ['Argelia'],
  'American Samoa': ['Samoa Americana'],
  Anguilla: ['Anguila'],
  Antarctica: ['Antártida'],
  'Antigua and Barbuda': ['Antigua y Barbuda', 'Antigua'],
  Azerbaijan: ['Azerbaiyán'],
  Bahrain: ['Baréin'],
  Bangladesh: ['Bangladés'],
  Belarus: ['Bielorrusia'],
  Belgium: ['Bélgica'],
  Belize: ['Belice'],
  Benin: ['Benín'],
  Bermuda: ['Bermudas'],
  Bhutan: ['Bután'],
  'Bosnia and Herzegovina': [
    'Bosnia y Herzegovina',
    'Bosnia-Herzegovina',
    'Bosnia',
  ],
  Botswana: ['Botsuana'],
  'Bouvet Island': ['Isla Bouvet'],
  Brazil: ['Brasil'],
  'British Indian Ocean Territory': ['Territorio Británico del Océano Índico'],
  'British Virgin Islands': ['Islas Vírgenes Británicas'],
  Brunei: ['Brunéi'],
  'Cabo Verde': ['Cape Verde'],
  Cambodia: ['Camboya'],
  Cameroon: ['Camerún'],
  Canada: ['Canadá'],
  'Caribbean Netherlands': ['Caribe neerlandés'],
  'Cayman Islands': ['Islas Caimán'],
  'Central African Republic': ['República Centroafricana'],
  'Christmas Island': ['Isla de Navidad'],
  'Cocos (Keeling) Islands': ['Islas Cocos'],
  Comoros: ['Comoras'],
  Congo: ['República del Congo', 'Congo-Brazzaville'],
  'Cook Islands': ['Islas Cook'],
  Croatia: ['Croacia'],
  Curaçao: ['Curazao'],
  Cyprus: ['Chipre'],
  Czechia: ['Chequia', 'República Checa', 'Czech Republic'],
  DRC: [
    'República Democrática del Congo',
    'RD Congo',
    'Congo-Kinsasa',
    'Democratic Republic of the Congo',
    'DR Congo',
  ],
  Denmark: ['Dinamarca'],
  Djibouti: ['Yibuti'],
  'Dominican Republic': ['República Dominicana'],
  Egypt: ['Egipto'],
  England: ['Inglaterra'],
  'Equatorial Guinea': ['Guinea Ecuatorial'],
  Eswatini: ['Esuatini', 'Suazilandia', 'Swaziland'],
  Ethiopia: ['Etiopía'],
  'Falkland Islands': ['Islas Malvinas', 'Falkland'],
  'Faroe Islands': ['Islas Feroe'],
  Fiji: ['Fiyi'],
  Finland: ['Finlandia'],
  France: ['Francia'],
  'French Guiana': ['Guayana Francesa'],
  'French Polynesia': ['Polinesia Francesa'],
  'French Southern and Antarctic Lands': [
    'Tierras Australes y Antárticas Francesas',
    'Territorios Australes Franceses',
  ],
  Gabon: ['Gabón'],
  Germany: ['Alemania'],
  Greece: ['Grecia'],
  Greenland: ['Groenlandia'],
  Grenada: ['Granada'],
  Guadeloupe: ['Guadalupe'],
  Guernsey: ['Guernesey'],
  'Guinea-Bissau': ['Guinea-Bisáu'],
  Haiti: ['Haití'],
  'Heard Island and McDonald Islands': [
    'Islas Heard y McDonald',
    'Isla Heard e Islas McDonald',
  ],
  Hungary: ['Hungría'],
  Iceland: ['Islandia'],
  Iran: ['Irán'],
  Iraq: ['Irak'],
  Ireland: ['Irlanda'],
  'Isle of Man': ['Isla de Man'],
  Italy: ['Italia'],
  'Ivory Coast': ['Costa de Marfil', "Côte d'Ivoire", 'Cote d Ivoire'],
  Japan: ['Japón'],
  Jordan: ['Jordania'],
  Kazakhstan: ['Kazajistán'],
  Kenya: ['Kenia'],
  Kyrgyzstan: ['Kirguistán'],
  Latvia: ['Letonia'],
  Lebanon: ['Líbano'],
  Lesotho: ['Lesoto'],
  Libya: ['Libia'],
  Lithuania: ['Lituania'],
  Luxembourg: ['Luxemburgo'],
  Macau: ['Macao'],
  Malawi: ['Malaui'],
  Malaysia: ['Malasia'],
  Maldives: ['Maldivas'],
  'Marshall Islands': ['Islas Marshall'],
  Martinique: ['Martinica'],
  Mauritius: ['Mauricio'],
  Mexico: ['México'],
  Moldova: ['Moldavia'],
  Monaco: ['Mónaco'],
  Morocco: ['Marruecos'],
  Myanmar: ['Birmania', 'Burma'],
  Netherlands: ['Países Bajos', 'Holanda'],
  'New Caledonia': ['Nueva Caledonia'],
  'New Zealand': ['Nueva Zelanda'],
  Niger: ['Níger'],
  'Norfolk Island': ['Isla Norfolk'],
  'North Korea': ['Corea del Norte'],
  'North Macedonia': ['Macedonia del Norte', 'Macedonia'],
  'Northern Ireland': ['Irlanda del Norte'],
  'Northern Mariana Islands': ['Islas Marianas del Norte'],
  Norway: ['Noruega'],
  Oman: ['Omán'],
  Pakistan: ['Pakistán'],
  Palau: ['Palaos'],
  Palestine: ['Palestina'],
  Panama: ['Panamá'],
  'Papua New Guinea': ['Papúa Nueva Guinea', 'Papúa'],
  Peru: ['Perú'],
  Philippines: ['Filipinas'],
  'Pitcairn Islands': ['Islas Pitcairn'],
  Poland: ['Polonia'],
  Qatar: ['Catar'],
  Romania: ['Rumanía'],
  Russia: ['Rusia'],
  Rwanda: ['Ruanda'],
  Réunion: ['Reunión'],
  'Saint Barthélemy': ['San Bartolomé', 'Saint Barthelemy'],
  'Saint Helena, Ascension and Tristan da Cunha': [
    'Santa Elena, Ascensión y Tristán de Acuña',
    'Santa Elena',
  ],
  'Saint Kitts and Nevis': [
    'San Cristóbal y Nieves',
    'Saint Kitts y Nevis',
    'Saint Kitts',
    'San Cristóbal',
  ],
  'Saint Lucia': ['Santa Lucía'],
  'Saint Martin': ['San Martín'],
  'Saint Pierre and Miquelon': ['San Pedro y Miquelón'],
  'Saint Vincent and the Grenadines': [
    'San Vicente y las Granadinas',
    'San Vicente',
  ],
  'Saudi Arabia': ['Arabia Saudí'],
  Scotland: ['Escocia'],
  'Sierra Leone': ['Sierra Leona'],
  Singapore: ['Singapur'],
  Slovakia: ['Eslovaquia'],
  Slovenia: ['Eslovenia'],
  'Solomon Islands': ['Islas Salomón'],
  'South Africa': ['Sudáfrica'],
  'South Georgia': [
    'Georgia del Sur',
    'Islas Georgias del Sur y Sandwich del Sur',
  ],
  'South Korea': ['Corea del Sur'],
  'South Sudan': ['Sudán del Sur'],
  Spain: ['España'],
  Sudan: ['Sudán'],
  Suriname: ['Surinam'],
  'Svalbard and Jan Mayen': ['Svalbard y Jan Mayen', 'Svalbard'],
  Sweden: ['Suecia'],
  Switzerland: ['Suiza'],
  Syria: ['Siria'],
  'São Tomé and Príncipe': ['Santo Tomé y Príncipe'],
  Taiwan: ['Taiwán'],
  Tajikistan: ['Tayikistán'],
  Thailand: ['Tailandia'],
  'Timor-Leste': ['Timor Oriental'],
  'Trinidad and Tobago': ['Trinidad y Tobago', 'Trinidad'],
  Tunisia: ['Túnez'],
  Turkey: ['Turquía', 'Türkiye'],
  Turkmenistan: ['Turkmenistán'],
  'Turks and Caicos Islands': ['Islas Turcas y Caicos'],
  Ukraine: ['Ucrania'],
  'United Arab Emirates': [
    'Emiratos Árabes Unidos',
    'Emiratos',
    'Emirates',
    'UAE',
    'EAU',
  ],
  'United Kingdom': ['Reino Unido', 'UK'],
  'United States': [
    'Estados Unidos',
    'EEUU',
    'EE.UU.',
    'EE. UU.',
    'USA',
    'Estados Unidos de America',
  ],
  'United States Minor Outlying Islands': [
    'Islas Ultramarinas Menores de Estados Unidos',
  ],
  'United States Virgin Islands': [
    'Islas Vírgenes de los Estados Unidos',
    'Islas Vírgenes de Estados Unidos',
    'Islas Vírgenes Americanas',
  ],
  Uzbekistan: ['Uzbekistán'],
  'Vatican City': [
    'Ciudad del Vaticano',
    'Vaticano',
    'Vatican',
    'Santa Sede',
    'Holy See',
  ],
  Wales: ['Gales'],
  'Wallis and Futuna': ['Wallis y Futuna'],
  'Western Sahara': ['Sáhara Occidental'],
  Zimbabwe: ['Zimbabue'],
  'Åland Islands': ['Islas Aland'],
};
